### PR TITLE
Adding Gitea- self hosted Git

### PR DESCRIPTION
**Pull request by ayush6624**
Hi,
I have added Gitea a self hosted Github
you can see their website [https://gitea.io](url)
Only thing is the SQL database is created inside the Docker container, so if one redeploys the app, all previous database is lost.
There is a documentation on their website to how to start with docker container [https://docs.gitea.io/en-us/install-with-docker/](url)

But being not so familiar with docker, i cant get it to work (I'm trying to make a separated Mysql/PostgreSQL ) container , and link their volumes of them (see the link above for how it is installed)

If anyone can make the db container(similar to how pg press's db container is processed), it would be great.

Anyways the container works flawlessly if db is hosted in itself and app not redeployed. Traefik is configured and available at git.domain.tld. Make sure to have the network settings shown in the attached image .
By default, the first user created becomes the admin
gitea

### CODE REVIEW

**Comment by Admin9705** [comment]
i'll add this, let me put this on a mini holding pattern, very awesome add :D

**Comment by Admin9705** [comment]
have time to check, the upside is i can deploy your fork and see haha

**Comment by Admin9705** [comment]
oh this nice! Really nice add, thank you!

**Comment by Admin9705** [comment]
at work, can merge, but will do when i get home

**Comment by Admin9705** [comment]
all i have to do is expose the container data and it should stay, but stuck where i cannot do that, but can work it.

**Comment by ayush6624** [comment]
No problem, you have made a fantastic app! :D

**Comment by Admin9705** [comment]
ok adding now

**Pull request merged**
