### PR TITLE
Adds nzbget-mp4 community app

### PR DESCRIPTION
**Pull request by DaRealestUK**
Still some testing needed, I believe you need to add your personal sonarr/radarr api key & docker network ip address to the autoProcess.ini file, once deployed.

With the option of using MP4 automator in sonarr or radarr, I used to get lots of issues with files got sometimes failing to process, or getting stuck before uploading. I remember having to exclude file types from the upload service and such things, which is not the easiest to setup. Plus the default aac encoder used to create artifacts for me.

With this option, the processing happens before the files are moved from the completed folder. Therefore no excludes needed for the upload service and no missed/stuck files.
ffmpeg builds inside the container, so get a better and glitch free audio.

I like to have the option to have my standard HD sonarr & radarr deployments to run MP4 automator via this, and use forks for 4k/HDR to bypass it.

On deployment, ffmpeg will build and may take a few mins. have a look in the portainer logs for completion. once complete, nzbget will launch.

on a restart, or watchtower update, ffmpeg will only build if there are changes for it to pick up.

### CODE REVIEW

**Comment by Admin9705** [comment]
oh this looks good, give me this week to check it out

**Comment by Admin9705** [comment]
ok adding!

**Comment by Admin9705** [comment]
but it won't push to the main one, which is 8.3 but i'll copy and paste it and unless you want to push it to that version

**Comment by DaRealestUK** [comment]
Hi there,

I found an issue with the current version on GitHub, but have fixed it
offline.

I will send another update.

**Comment by Admin9705** [comment]
Will so. Thanks for the awesome work

**Comment by Admin9705** [comment]
just checking in @DaRealestUK

**Comment by DaRealestUK** [comment]
Okay,

just fixed all issues, but in testing have found a new issue with an update to the build-ffmpeg script.
Reported here: https://github.com/markus-perl/ffmpeg-build-script/issues/23

**Comment by DaRealestUK** [comment]
Okay, made a quick modification to exclude the needed part from that ffmpeg build script. will added extra commits to my patch-1 branch

**Comment by DaRealestUK** [comment]
okay, I think it's working now

**Comment by DaRealestUK** [comment]
okay, done one last tweak. set default bypass categorises in script file instead of role. So that redeployment does not alter user's setting changes

**Comment by DaRealestUK** [comment]
Okay, all the testing I have done is based on Pg v 8.1. I was planning and skipping over 8.2 and going directly to 8.3, which I see is final now.
I have just read through the changelog on the homepage and see redeployment of nzbget is needed. Therefore I will need to compare any upstream changes to the role, before I upgrade my server to 8.3 and re-test deployment.

**Comment by Admin9705** [comment]
no problem, 8.3+ should be pretty well set. 8-0 / 8-2 was battling mount changes.

**Comment by DaRealestUK** [comment]
Okay, done a quick compare and put in a role for 8.3+. Have yet to test this though

**Comment by Admin9705** [comment]
it's fine, just send it

**Comment by DaRealestUK** [comment]
Already have (above my last comment)

**Comment by robertbaker** [comment]
Make sure you do extensive testing with a clean install or you'll get people complaining!

**Comment by robertbaker** [comment]
You'll need to update the include tasks in your yml, as they point to the wrong location.

**Comment by DaRealestUK** [comment]
Sorry, this is the first time I have actually used GitHub.
I though that by committing to the patch-1 branch, created from my initial merge request on the official community repo, would update the merge request...
It says above here: Add more commits by pushing to the `[patch-1](/DaRealestUK/PlexGuide-Community/tree/patch-1)` branch on [DaRealestUK/PlexGuide-Community](/DaRealestUK/PlexGuide-Community).

**Comment by robertbaker** [comment]
find: /opt/plexguide/containers

replace: /opt/communityapps/apps

**Pull request closed without merging**
